version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /symbiota
    volumes:
      - ./:/symbiota
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php:
    build: ./docker/php-fpm
    container_name: php
    working_dir: /symbiota
    volumes:
      - ./:/symbiota
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota
    ports:
      - 3308:3306
